# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ytOITpoavtt7AD6E1sTT4skYBsu1ddC
"""

from google.colab import files
uploaded = files.upload()

import os
print(os.listdir())

import os
print(os.listdir())

import pandas as pd

df = pd.read_csv("comments.csv")  # غيّر الاسم إذا كان مختلفًا
print(df.head())
print(df.columns)
print(df.shape)

import re

df = df[["Text"]].copy()
df.dropna(inplace=True)

df["Text"] = df["Text"].astype(str).str.strip()

def clean_text(text):
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"#", "", text)
    text = re.sub(r"\d+", "", text)
    text = re.sub(r"[^\u0600-\u06FF\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df["text"] = df["Text"].apply(clean_text)

df = df[df["text"] != ""]
df = df[df["text"].str.len() > 2]
df.drop_duplicates(subset=["text"], inplace=True)
df.reset_index(drop=True, inplace=True)

print("بعد التنظيف:", df.shape)
df.head()

from datasets import load_dataset

dataset = load_dataset("ajgt_twitter_ar")

print(dataset)
print(dataset["train"][0])

import numpy as np
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer

# تحويل البيانات إلى Dataset
train_dataset = dataset["train"]

# تقسيم Train/Test
train_test = train_dataset.train_test_split(test_size=0.2)

train_dataset = train_test["train"]
test_dataset = train_test["test"]

# تحميل AraBERT
model_name = "aubmindlab/bert-base-arabertv02"

tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

train_dataset = train_dataset.map(tokenize_function, batched=True)
test_dataset = test_dataset.map(tokenize_function, batched=True)

train_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])
test_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])

# تحميل النموذج
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

# التقييم
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    accuracy = (preds == labels).mean()
    return {"accuracy": accuracy}

# إعداد التدريب
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    logging_steps=50,
    save_strategy="epoch",
    report_to=[]
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

# التدريب 🔥
trainer.train()

# التقييم
results = trainer.evaluate()
print(results)

# حفظ النموذج
model.save_pretrained("final_model")
tokenizer.save_pretrained("final_model")

print("تم حفظ النموذج ✅")

import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

texts = [
    "الخدمة ممتازة جدا",
    "التطبيق سيء للغاية",
    "التجربة رائعة",
    "لا أنصح بهذا المنتج",
    "جيد لكن يحتاج تحسين"
]

for text in texts:
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)

    # 👇 ننقل البيانات للـ GPU
    inputs = {key: val.to(device) for key, val in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)

    pred = outputs.logits.argmax().item()

    if pred == 1:
        result = "إيجابي"
    else:
        result = "سلبي"

    print(f"{text} --> {result}")

import torch
import gradio as gr

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

def predict_sentiment(text):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=128
    )
    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)

    probs = torch.softmax(outputs.logits, dim=1)
    pred = torch.argmax(probs, dim=1).item()
    confidence = probs[0][pred].item()

    sentiment = "إيجابي" if pred == 1 else "سلبي"
    return f"التصنيف: {sentiment}\nالثقة: {round(confidence * 100, 2)}%"

demo = gr.Interface(
    fn=predict_sentiment,
    inputs=gr.Textbox(lines=3, placeholder="اكتب تعليقًا هنا..."),
    outputs="text",
    title="Arabic Sentiment Analysis with AraBERT",
    description="اكتب نصًا عربيًا وسيقوم النموذج بتصنيفه إلى إيجابي أو سلبي مع نسبة الثقة"
)

demo.launch(share=True)

from google.colab import drive
drive.mount('/content/drive')

!cp -r final_model /content/drive/MyDrive/

!zip -r project.zip final_model *.ipynb *.csv

